export const TYPES = {
  /*****DB PRODUCTS *****/
  CREATE_DATA: "CREATE_DATA",
  READ_STATE: "READ_STATE",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",

  /***** SHOPPING CART *****/
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ONE_PRODUCT: "REMOVE_ONE_PRODUCT",
  REMOVE_ALL_PRODUCTS: "REMOVE_ALL_PRODUCTS",
  CLEAR_CART: "CLEAR_CART",
};
