import   React      from "react";
import   Head       from "next/head";
import { Inter }    from "next/font/google";
import   NavBar     from "@/components/navBar/NavBar";
import   Footer     from "@/components/footer/Footer";


const inter = Inter({ subsets: ['latin'] })

const Contacto = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name  ="description"  content ="Generated by create next app" />
                <meta name  ="viewport"     content ="width=device-width, initial-scale=1" />
                <link rel   ="icon"         href    ="/favicon.ico" />
            </Head>
            <header>
                <NavBar />
            </header>
            <main>
                <div>Contacto</div>
                <Footer />
            </main>
        </>
    )
}

export default Contacto;