import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/navBar/NavBar'
import CardSectionComunidad from '@/components/cardSectionIndex/CardSectionComunidad'
import HeaderHome from '@/components/HeaderHome'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <NavBar />
        <HeaderHome />
        <CardSectionComunidad />
      </header>
      <main>
      </main>
    </>
  )
}
