
import React from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import NavBar from "@/components/navBar/NavBar";
import Shop from "@/components/Shop/Shop";
import ShoppingCart from "@/components/Shop/ShoppingCart";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

const Tienda = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous"
        ></link>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
          crossorigin="anonymous"
        ></script>
      </Head>
      <header>
        <NavBar />
      </header>
      <main>
        <div
          id="carouselExampleInterval"
          class="carousel slide"
          data-bs-ride="carousel"
        >
          <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="10000">
              <img
                src="https://http2.mlstatic.com/D_NQ_661703-MLA72380165087_102023-OO.webp"
                class="d-block w-100"
                alt="Banner1"
              ></img>
            </div>
            <div class="carousel-item" data-bs-interval="2000">
              <img
                src="https://http2.mlstatic.com/D_NQ_729407-MLA72367625788_102023-OO.webp"
                class="d-block w-100"
                alt="Banner2"
              ></img>
            </div>
            <div class="carousel-item">
              <img
                src="https://http2.mlstatic.com/D_NQ_600478-MLA71695942513_092023-OO.webp"
                class="d-block w-100"
                alt="Banner3"
              ></img>
            </div>
          </div>
          <button
            class="carousel-control-prev"
            type="button"
            data-bs-target="#carouselExampleInterval"
            data-bs-slide="prev"
          >
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button
            class="carousel-control-next"
            type="button"
            data-bs-target="#carouselExampleInterval"
            data-bs-slide="next"
          >
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <ShoppingCart />
      </main>
    </>
  );
};




const inter = Inter({ subsets: ['latin'] })

const Tienda=()=> {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name  ="description"  content ="Generated by create next app" />
                <meta name  ="viewport"     content ="width=device-width, initial-scale=1" />
                <link rel   ="icon"         href    ="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"></link>
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
                
            </Head>
            <header>
                <NavBar />
            </header>
            <main>

                <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active" data-bs-interval="10000">
                            <img src="https://http2.mlstatic.com/D_NQ_661703-MLA72380165087_102023-OO.webp" class="d-block w-100" alt="Banner1"></img>
                        </div>
                        <div class="carousel-item" data-bs-interval="2000">
                            <img src="https://http2.mlstatic.com/D_NQ_729407-MLA72367625788_102023-OO.webp" class="d-block w-100" alt="Banner2"></img>
                        </div>
                        <div class="carousel-item">
                            <img src="https://http2.mlstatic.com/D_NQ_600478-MLA71695942513_092023-OO.webp" class="d-block w-100" alt="Banner3"></img>
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
                <ShoppingCart />
            </main>
        </>
    )
}

export default Tienda;
