import Head from 'next/head'
import React from 'react'
import { Inter } from 'next/font/google'
import NavBar from '@/components/navBar/NavBar'

const inter = Inter({ subsets: ['latin'] })

const Tienda = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <NavBar />

            </header>
            <main>
                <div>Tienda</div>
            
            </main>
        </>
    )
}

export default Tienda