import React 	from "react";
import Head		from "next/head";
import NavBar 	from "@/components/navBar/NavBar";
import Footer 	from "@/components/footer/Footer";
// --------❀(Para mayor Legibilidad, configurar sangria por 4 espacios)❀--------

const UsuariosPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name	="description"	content	="Generated by create next app" />
				<meta name	="viewport"		content	="width=device-width, initial-scale=1" />
				<link rel	="icon"			href	="/favicon.ico"	/>
			</Head>
			<header> <NavBar /> </header>
			<main>
				<div>usuarios</div>

				<div className="usuarios-page">
{/* ☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷Login* */}
					<div className="login-section">
						<div className="section-content">
							<h1>Iniciar Sesión</h1>
							<form>
								<div className		="input-group">
									<label htmlFor	="username">
													Usuario:
									</label>
									<input	type	="text"
											id		="username"
											name	="username" />
								</div>
								<div className		="input-group">
									<label htmlFor	="password">
													Contraseña:
									</label>
									<input	type	="password"
											id		="password"
											name	="password" />
								</div>
								<div className		="input-group">
									<label htmlFor	="remember-username">
													Recordar mi usuario
									</label>
									<input 	type	="checkbox"
											id		="remember-username"
										className	="checkbox" />
								</div>
								<div className		="input-group">
									<label htmlFor	="remember-password">
													Recordar contraseña
									</label>
									<input 	type	="checkbox"
											id		="remember-password" />
								</div>
								<button	className	="boton-login"
											type	="submit">
													Iniciar Sesión
								</button>
							</form>
						</div>
					</div>
{/* ☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷Registro* */}
					<div className="registro-section">
						<div className="section-content">
							<h1>Registro</h1>
							<form>
								<div className		="input-group">
									<label htmlFor	="register-username">
													Usuario:
									</label>
									<input	type	="text"
											id		="register-username"
											name	="register-username" />
								</div>
								<div className		="input-group">
									<label htmlFor	="email">
													E-mail:
									</label>
									<input 	type	="email"
											id		="email"
											name	="email"/>
								</div>
								<div className		="input-group">
									<label htmlFor	="register-password">
													Contraseña:
									</label>
									<input 	type	="password"
											id		="register-password"
											name	="register-password" />
								</div>
								<div className		="input-group">
									<label htmlFor	="confirm-password">
													Confirmar Contraseña:
									</label>
									<input	type	="password" 
											id		="confirm-password"
											name	="confirm-password" />
								</div>
								<button	className	="boton-registro"
											type	="submit">
													Registrarse
								</button>
							</form>
						</div>
					</div>
				</div>
{/* ☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷☷Estilos* */}
				<style jsx>{`
					.usuarios-page
					{ 	display: 					grid;
						grid-template-columns: 	repeat(auto-fit, minmax(200px, 1fr));
						justify-items:			center;
						align-items: 			space-evenly;
						color: 					#ffffff;
						margin: 				50px}

					.section-content
					{ 	text-align: 			center;
						margin-top: 			10px;}

					.login-section
					{	background-image: 		url(/img/fondo-sesion.png);
						height: 				300px;
						width: 					200px;
						border-radius: 			15px}

					.registro-section
					{	background-image: 		url(/img/fondo-registro.png);
						height: 				300px;
						width: 					200px;
						border-radius: 			15px}
					
					.input-group
					{	margin-bottom:			10px;
						display:				grid;
						place-content:			space-around}

					.boton-login
					{	margin-bottom: 			50px;
						padding: 				10px 20px;
						border-radius: 			50px;
						border: 				0;
						background-color: 		#F22E42;
						box-shadow: 			rgb(0 0 0 / 5%) 0 0 8px;
						letter-spacing: 		1.5px;
						text-transform: 		uppercase;
						font-size: 				15px;
						color: 					#ffffff;
						transition: 			all .3s ease;
						margin-bottom: 			15px;}
					
					.boton-login:hover
					{	letter-spacing: 		3px;
						background-color: 		#172556;
						color: 					hsl(0, 0%, 100%);
						box-shadow: 			#F22E42 0px 7px 29px 0px;}
					
					.boton-login:active
					{	letter-spacing: 		3px;
						background-color: 		hsl(261deg 80% 48%);
						color: 					hsl(0, 0%, 100%);
						box-shadow: 			#F22E42 0px 0px 0px 0px;
						transform: 				translateY(10px);
						transition: 			100ms;}

					.boton-registro
					{	margin-bottom: 			50px;
						padding: 				10px 20px;
						border-radius: 			50px;
						border: 				0;
						background-color: 		#172556;
						box-shadow: 			rgb(0 0 0 / 5%) 0 0 8px;
						letter-spacing: 		1.5px;
						text-transform: 		uppercase;
						font-size: 				15px;
						color: 					#ffffff;
						transition: 			all .3s ease;
						margin-bottom: 			15px;}
					
					.boton-registro:hover
					{	letter-spacing: 		3px;
						background-color: 		#F22E42;
						color: 					hsl(0, 0%, 100%);
						box-shadow: 			#172556 0px 7px 29px 7px;}
					
					.boton-registro:active
					{	letter-spacing: 		3px;
						background-color: 		hsl(261deg 80% 48%);
						color: 					hsl(0, 0%, 100%);
						box-shadow: 			#F22E42 5px 5px 5px 5px;
						transform: 				translateY(10px);
						transition: 			100ms;}
				`}</style>

				<Footer />
			</main>
		</>
	);
};

export default UsuariosPage;
